#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
Rscript -e "rmarkdown::render(input = '{{ test }}.Rmd', output_dir = '../results', clean = TRUE, output_format = 'html_document')"

# The previous version of this file was commented-out and follows below:
#
# Rscript {{ test }}.R "$@"
