---
title: "Wilcoxon test for `{{ dv }}` ~ `{{ iv }}`"
author: {{ author }} <{{ email }}>
comment: This file is automatically generate by Shiny-Statistic app (https://statistic.geiser.tech/)
         Author - Geiser C. Challco <geiser@usp.br>
         
         Shiny-Statistic is distributed in the hope that it will be useful,
         but WITHOUT ANY WARRANTY; without even the implied warranty of
         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         GNU General Public License for more details.
         
         You should have received a copy of the GNU General Public License.
         If not, see <https://www.gnu.org/licenses/>.
output:
  github_document: default
  word_document: default
  html_document: default
  pdf_document:
    keep_tex: true
fontsize: 10pt
---

```{r setup, include=FALSE}
if (!'remotes' %in% rownames(installed.packages())) install.packages('remotes')
if (!"rshinystatistics" %in% rownames(installed.packages())) {
  remotes::install_github("geiser/rshinystatistics")
} else if (packageVersion("rshinystatistics") < "{{ rshinystatistics.version }}") {
  remotes::install_github("geiser/rshinystatistics")
}

wants <- c('ggplot2','ggpubr','rshinystatistics','car','stats','rstatix','utils','dplyr','knitr')
has <- wants %in% rownames(installed.packages())
if (any(!has)) install.packages(wants[!has])

library(knitr)
opts_chunk$set(echo = TRUE)

library(utils)
library(ggpubr)
library(ggplot2)
library(rstatix)
library(rshinystatistics)

defaultW <- getOption("warn")
options(warn = -1)

dat <- read.csv("data.csv")
rownames(dat) <- dat[["{{ wid }}"]]
```

## Initial Data and R-Script

* Initial data: [data.csv](data.csv)
* R-script file: [wilcoxon.R](wilcoxon.R)

### Identifying outliers

* Identified outliers using rstatix

```{r}
identify_outliers(dplyr::group_by(dat, `{{ iv }}`), `{{ dv }}`)
```

* Identified outliers through Boxplots

```{r}
car::Boxplot(`{{ dv }}` ~ `{{ iv }}`, data = dat, id = list(n = Inf))
```

### Removing outliers from the data

```{r}
outliers <- c({{ paste0(paste0('"',outlier.ids,'"'),collapse = ',') }})
sdat <- dat[!dat[["{{ wid }}"]] %in% outliers,]
```

## Computation wilcoxon test and effect size

```r
res <- wilcoxon_test(sdat, "{{ dv }}", "{{ iv }}", "{{ alternative }}", as.list=T)
(res$wilcoxon.test)
```

```{r echo=FALSE}
res <- wilcoxon_test(sdat, "{{ dv }}", "{{ iv }}", "{{ alternative }}", as.list=T)
kdf <- res$wilcoxon.test[,c(
  ".y.", "group1", "group2", "n1", "n2","statistic", "estimate",
  "conf.low", "conf.high", "effsize", "magnitude", "p","p.signif")]
kdf$p <- round(kdf$p, 3)
kdf$p[which(kdf$p < 0.001)] <- '<0.001'
kable(kdf, digits = 3)
```

## Descriptive Statistic and Wilcoxon Plots 

```r
descriptive_statistics(sdat, "{{ dv }}", "{{ iv }}", "common")
```

```{r echo=FALSE}
kdf <- descriptive_statistics(sdat, "{{ dv }}", "{{ iv }}", "common")
cnames <- c("variable",iv,"n","median","mean","min","max","iqr","sd")
kdf <- kdf[,cnames]
kable(kdf, digits = 3)
```


```{r, fig.width={{ ceiling(width/100) }}, fig.height={{ ceiling(height/100) }} }
ggPlotWilcoxon(sdat, "{{ iv }}", "{{ dv }}", res$wt[["{{ dv }}"]], c({{ paste0(paste0('"',addParam,'"'),collapse=',') }}), font.label.size={{ font.label.size }})
```

