---
title: "Wilcoxon test for {{ paste0(paste0('`', dvs, '`'), collapse = ',') }} with `{{ iv }}`"
author: {{ author }} <{{ email }}>
comment: This file is automatically generate by Shiny-Statistic app (https://statistic.geiser.tech/)
         Author - Geiser C. Challco <geiser@usp.br>
         
         Shiny-Statistic is distributed in the hope that it will be useful,
         but WITHOUT ANY WARRANTY; without even the implied warranty of
         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         GNU General Public License for more details.
         
         You should have received a copy of the GNU General Public License.
         If not, see <https://www.gnu.org/licenses/>.
output:
  github_document: default
  word_document: default
  html_document: default
  pdf_document:
    keep_tex: true
fontsize: 10pt
---

```{r setup, include=FALSE}
if (!'remotes' %in% rownames(installed.packages())) install.packages('remotes')
if (!"rshinystatistics" %in% rownames(installed.packages())) {
  remotes::install_github("geiser/rshinystatistics")
} else if (packageVersion("rshinystatistics") < "{{ rshinystatistics.version }}") {
  remotes::install_github("geiser/rshinystatistics")
}

wants <- c('ggplot2','ggpubr','rshinystatistics','utils', 'knitr')
has <- wants %in% rownames(installed.packages())
if (any(!has)) install.packages(wants[!has])

library(knitr)
opts_chunk$set(echo = TRUE)

library(utils)
library(ggpubr)
library(ggplot2)
library(rshinystatistics)

defaultW <- getOption("warn")
options(warn = -1)
```

## Initial Data and Script

* R-script file: [wilcoxon.R](wilcoxon.R)
{{ paste0(paste0('* Data for ', dvs, ' [data-',dvs,'.csv](data-',dvs,'.csv)'), collapse = '\n') }}


### Setting identificator, dependent and independent variables

```{r}
dvs <- c({{ paste0(paste0('"', dvs, '"'), collapse = ',') }})
iv <- "{{ iv }}"
wid <- "{{ wid }}"
ldvs <- as.list(dvs); names(ldvs) <- dvs
dat <- lapply(ldvs, FUN = function(dv) {
  data <- read.csv(paste0("data-",dv,".csv"))
  rownames(data) <- data[["{{ wid }}"]]
  return(data)
})
```

## Removing outliers from the data

```{r}
outliers <- {{ code.outliers }}
sdat <- remove_from_datatable(dat, outliers, wid, "var")
```

## Computation Wilcoxon Test and effect size

```r
res <- wilcoxon_test(sdat, dvs, iv, "{{ alternative }}", dv.var='var', as.list=T)
(res$wilcoxon.test)
```

```{r echo=FALSE}
res <- wilcoxon_test(sdat, dvs, iv, "{{ alternative }}", dv.var='var', as.list=T)
kdf <- res$wilcoxon.test[,c(
  ".y.", "group1", "group2", "n1", "n2","statistic", "estimate",
  "conf.low", "conf.high", "effsize", "magnitude", "p","p.signif")]
kdf$p <- round(kdf$p, 3)
kdf$p[which(kdf$p < 0.001)] <- '<0.001'
kable(kdf, digits = 3)
```

## Descriptive Statistic and Wilcoxon Plots 

```r
descriptive_statistics(sdat, dvs, iv, "common", "var")
```

```{r echo=FALSE}
kdf <- descriptive_statistics(sdat, dvs, iv, "common", "var")
cnames <- c("variable",iv,"n","median","mean","min","max","iqr","sd")
kdf <- kdf[,cnames]
kable(kdf, digits = 3)
```

{{ wtest.plots  }}
